// Pronunciation guide for country names (IPA-style phonetic notation)
export const pronunciations = {
  // Common countries
  'Afghanistan': '/æfˈɡænɪstæn/',
  'Albania': '/ælˈbeɪniə/',
  'Algeria': '/ælˈdʒɪəriə/',
  'Argentina': '/ˌɑːrdʒənˈtiːnə/',
  'Australia': '/ɒˈstreɪliə/',
  'Austria': '/ˈɒstriə/',
  'Bangladesh': '/ˌbæŋɡləˈdɛʃ/',
  'Belgium': '/ˈbɛldʒəm/',
  'Brazil': '/brəˈzɪl/',
  'Canada': '/ˈkænədə/',
  'Chile': '/ˈtʃɪli/',
  'China': '/ˈtʃaɪnə/',
  'Colombia': '/kəˈlʌmbiə/',
  'Croatia': '/kroʊˈeɪʃə/',
  'Cuba': '/ˈkjuːbə/',
  'Denmark': '/ˈdɛnmɑːrk/',
  'Egypt': '/ˈiːdʒɪpt/',
  'Ethiopia': '/ˌiːθiˈoʊpiə/',
  'Finland': '/ˈfɪnlənd/',
  'France': '/fræns/',
  'Germany': '/ˈdʒɜːrməni/',
  'Greece': '/ɡriːs/',
  'Iceland': '/ˈaɪslənd/',
  'India': '/ˈɪndiə/',
  'Indonesia': '/ˌɪndəˈniːʒə/',
  'Iran': '/ɪˈrɑːn/',
  'Iraq': '/ɪˈrɑːk/',
  'Ireland': '/ˈaɪərlənd/',
  'Israel': '/ˈɪzreɪəl/',
  'Italy': '/ˈɪtəli/',
  'Japan': '/dʒəˈpæn/',
  'Jordan': '/ˈdʒɔːrdən/',
  'Kenya': '/ˈkɛnjə/',
  'Kuwait': '/kʊˈweɪt/',
  'Lebanon': '/ˈlɛbənən/',
  'Libya': '/ˈlɪbiə/',
  'Malaysia': '/məˈleɪʒə/',
  'Mexico': '/ˈmɛksɪkoʊ/',
  'Morocco': '/məˈrɒkoʊ/',
  'Nepal': '/nəˈpɔːl/',
  'Netherlands': '/ˈnɛðərləndz/',
  'New Zealand': '/njuː ˈziːlənd/',
  'Nigeria': '/naɪˈdʒɪəriə/',
  'Norway': '/ˈnɔːrweɪ/',
  'Pakistan': '/ˈpækɪstæn/',
  'Peru': '/pəˈruː/',
  'Philippines': '/ˈfɪlɪpiːnz/',
  'Poland': '/ˈpoʊlənd/',
  'Portugal': '/ˈpɔːrtʃəɡəl/',
  'Qatar': '/ˈkætɑːr/',
  'Romania': '/roʊˈmeɪniə/',
  'Russia': '/ˈrʌʃə/',
  'Saudi Arabia': '/ˌsaʊdi əˈreɪbiə/',
  'Singapore': '/ˈsɪŋəpɔːr/',
  'South Africa': '/saʊθ ˈæfrɪkə/',
  'South Korea': '/saʊθ kəˈriːə/',
  'Spain': '/speɪn/',
  'Sweden': '/ˈswiːdən/',
  'Switzerland': '/ˈswɪtsərlənd/',
  'Syria': '/ˈsɪriə/',
  'Taiwan': '/ˌtaɪˈwɑːn/',
  'Thailand': '/ˈtaɪlænd/',
  'Turkey': '/ˈtɜːrki/',
  'Ukraine': '/juːˈkreɪn/',
  'United Arab Emirates': '/juːˌnaɪtɪd ˌærəb ˈɛmɪrəts/',
  'United Kingdom': '/juːˌnaɪtɪd ˈkɪŋdəm/',
  'United States': '/juːˌnaɪtɪd ˈsteɪts/',
  'Uruguay': '/ˈjʊərəɡwaɪ/',
  'Venezuela': '/ˌvɛnəˈzweɪlə/',
  'Vietnam': '/ˌviːɛtˈnæm/',
  'Yemen': '/ˈjɛmən/',
  'Zimbabwe': '/zɪmˈbɑːbweɪ/',
}

// Get pronunciation for a country, or generate a default one
export const getPronunciation = (countryName) => {
  return pronunciations[countryName] || `/${countryName.toLowerCase()}/`
}
